/*
 * Calculator.h
 *
 *  Created on: Aug 30, 2022
 *      Author: ahmad
 */

#ifndef INC_CALCULATOR_H_
#define INC_CALCULATOR_H_


#define CALCULATOR_BUTTON_NUM0      KEYPAD_BUTTON01
#define CALCULATOR_BUTTON_NUM1      KEYPAD_BUTTON04
#define CALCULATOR_BUTTON_NUM2      KEYPAD_BUTTON05
#define CALCULATOR_BUTTON_NUM3      KEYPAD_BUTTON06
#define CALCULATOR_BUTTON_NUM4      KEYPAD_BUTTON08
#define CALCULATOR_BUTTON_NUM5      KEYPAD_BUTTON09
#define CALCULATOR_BUTTON_NUM6      KEYPAD_BUTTON10
#define CALCULATOR_BUTTON_NUM7      KEYPAD_BUTTON12
#define CALCULATOR_BUTTON_NUM8      KEYPAD_BUTTON13
#define CALCULATOR_BUTTON_NUM9      KEYPAD_BUTTON14
#define CALCULATOR_BUTTON_PLUS      KEYPAD_BUTTON03
#define CALCULATOR_BUTTON_MINUS     KEYPAD_BUTTON07
#define CALCULATOR_BUTTON_MUL       KEYPAD_BUTTON11
#define CALCULATOR_BUTTON_DIV       KEYPAD_BUTTON15
#define CALCULATOR_BUTTON_CLR       KEYPAD_BUTTON00
#define CALCULATOR_BUTTON_EQUAL     KEYPAD_BUTTON02

void Calculator_Run(void);
u8 Calculator_GetRealNumber (Keypad_ButtonType button);






#endif /* INC_CALCULATOR_H_ */
